export interface Cuestionario {
    idCuestionario?: number;
    titulo:string;
    pregunta1: string;
    respuesta11: string;
    respuesta12: string;
    respuesta13: string;
    respuesta14: string;
    pregunta2: string;
    respuesta21: string;
    respuesta22: string;
    respuesta23: string;
    respuesta24: string;
    pregunta3: string;
    respuesta31: string;
    respuesta32: string;
    respuesta33: string;
    respuesta34: string;
    pregunta4: string;
    respuesta41: string;
    respuesta42: string;
    respuesta43: string;
    respuesta44: string;
    pregunta5: string;
    respuesta51: string;
    respuesta52: string;
    respuesta53: string;
    respuesta54: string;
    pregunta6: string;
    respuesta61: string;
    respuesta62: string;
    respuesta63: string;
    respuesta64: string;
    pregunta7: string;
    respuesta71: string;
    respuesta72: string;
    respuesta73: string;
    respuesta74: string;
    pregunta8: string;
    respuesta81: string;
    respuesta82: string;
    respuesta83: string;
    respuesta84: string;
    pregunta9: string;
    respuesta91: string;
    respuesta92: string;
    respuesta93: string;
    respuesta94: string;
    pregunta10: string;
    respuesta101: string;
    respuesta102: string;
    respuesta103: string;
    respuesta104: string;

  }
  